version: '3.8'
services:
  main-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - store-db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://store-db:5432/store-electronics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  store-db:
    image: postgres:13.7-alpine
    container_name: store-db
    ports:
      - "6541:5432"
    restart: on-failure
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=store-electronics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: YandexStore23
    ports:
      - "5050:80"